apiVersion: v2
name: rainbond
description: Rainbond Helm chart
type: application
version: 6.0.0
appVersion: v6
icon: https://www.rainbond.com/images/rainbondlog.png
home: https://github.com/goodrain/rainbond
sources:
  - https://github.com/goodrain/rainbond
