apiVersion: rainbond.io/v1alpha1
kind: RainbondVolume
metadata:
  labels:
    accessModes: rwx
    belongTo: rainbond-operator
    creator: Rainbond
  name: rainbondvolumerwx
  namespace: rbd-system
spec:
{{- if .Values.Cluster.RWX.enable  }}
  {{- if eq .Values.Cluster.RWX.type "aliyun" }}
  storageClassParameters:
    mountOptions:
    - "nolock,tcp,noresvport"
    - "vers=4"
    - "minorversion=0"
    - "rsize=1048576"
    - "wsize=1048576"
    - "timeo=600"
    - "retrans=2"
    - "hard"
    parameters:
      volumeAs: subpath
      archiveOnDelete: "true"
      server: {{ .Values.Cluster.RWX.config.server}}
  {{- else }}
  storageClassName: {{ .Values.Cluster.RWX.config.storageClassName | quote }}
  {{- end }}
{{- else }}
  csiPlugin:
    nfs: {}
  storageRequest: 1
{{- end }}
  imageRepository: registry.cn-hangzhou.aliyuncs.com/goodrain
