#############################################
# 
# Copyright 2023 Goodrain Co., Ltd.
# 
# This version of the GNU Lesser General Public License incorporates
# the terms and conditions of version 3 of the GNU General Public License.
# 
#############################################

apiVersion: v1
items:
- apiVersion: rainbond.io/v1alpha1
  kind: RainbondCluster
  metadata:
    name: rainbondcluster
    namespace: {{ .Release.Namespace }}
  spec:
    enableHA: {{ .Values.Cluster.enableHA }}
    configCompleted: true
{{- if .Values.Cluster.gatewayIngressIPs }}
    gatewayIngressIPs:
    - {{ .Values.Cluster.gatewayIngressIPs }}
{{- else }}
{{ end }}
{{- if .Values.Cluster.imageHub.enable  }}
    imageHub:
      domain: {{ .Values.Cluster.imageHub.domain | quote }}
      password: {{ .Values.Cluster.imageHub.password | quote }}
      username: {{ .Values.Cluster.imageHub.username | quote }}
      namespace: {{ .Values.Cluster.imageHub.namespace | quote }} 
{{- end }}
{{- if .Values.Cluster.RWO.enable  }} 
    rainbondVolumeSpecRWO:
      storageClassName: {{ .Values.Cluster.RWO.storageClassName | quote }}
      imageRepository: {{ .Values.Cluster.rainbondImageRepository }}
{{- end }}
{{- if .Values.Cluster.RWX.enable  }} 
    rainbondVolumeSpecRWX:
      {{- if eq .Values.Cluster.RWX.type "aliyun" }}
      storageClassParameters:
        mountOptions:
        - "nolock,tcp,noresvport"
        - "vers=4"
        - "minorversion=0"
        - "rsize=1048576"
        - "wsize=1048576"
        - "timeo=600"
        - "retrans=2"
        - "hard"
        parameters:
          volumeAs: subpath
          archiveOnDelete: "true"
          server: {{ .Values.Cluster.RWX.config.server }}
        provisioner: nasplugin.csi.alibabacloud.com
      {{- else }}
      storageClassName: {{ .Values.Cluster.RWX.config.storageClassName | quote }}
      {{- end }}
      imageRepository: {{ .Values.Cluster.rainbondImageRepository }}
{{- end }}
{{- if .Values.Cluster.regionDatabase.enable }}
    regionDatabase:
      host: {{  required ".Values.Cluster.regionDatabase.host cannot be empty!" .Values.Cluster.regionDatabase.host }}
      name: {{ .Values.Cluster.regionDatabase.name | quote }}
      password: {{ .Values.Cluster.regionDatabase.password | quote }}
      port: {{ .Values.Cluster.regionDatabase.port }}
      username: {{ .Values.Cluster.regionDatabase.username | quote }}
{{- end }}
{{- if .Values.Cluster.uiDatabase.enable }}
    uiDatabase:
      host: {{ required ".Values.Cluster.uiDatabase.host cannot be empty!" .Values.Cluster.uiDatabase.host }}
      name: {{ .Values.Cluster.uiDatabase.name | quote }}
      password: {{ .Values.Cluster.uiDatabase.password | quote }}
      port: {{ .Values.Cluster.uiDatabase.port }}
      username: {{ .Values.Cluster.uiDatabase.username | quote }}
{{- end }}
    suffixHTTPHost: ""
    installMode: WithoutPackage
    installVersion: {{ .Values.Cluster.installVersion }}     
{{- if .Values.Cluster.nodesForChaos }}
    nodesForChaos:
{{ .Values.Cluster.nodesForChaos | toYaml | indent 4 }}
{{- else }}
{{ end }}
{{- if .Values.Cluster.nodesForGateway }}
    nodesForGateway:
{{ .Values.Cluster.nodesForGateway | toYaml | indent 4 }}
{{- else }}
{{ end }}
    rainbondImageRepository: {{ .Values.Cluster.rainbondImageRepository }}

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
