#############################################
# 
# Copyright 2023 Goodrain Co., Ltd.
# 
# This version of the GNU Lesser General Public License incorporates
# the terms and conditions of version 3 of the GNU General Public License.
# 
#############################################

apiVersion: v1
items:
- apiVersion: rainbond.io/v1alpha1
  kind: RainbondCluster
  metadata:
    name: rainbondcluster
    namespace: {{ .Release.Namespace }}
  spec:
    gatewayIngressIPs: 
    - {{ .Values.Cluster.gatewayIngressIPs }}
{{- if .Values.Cluster.imageHub.enable  }}
    imageHub:
      domain: {{ .Values.Cluster.imageHub.domain | quote }}
      password: {{ .Values.Cluster.imageHub.password | quote }}
      username: {{ .Values.Cluster.imageHub.username | quote }}
      namespace: {{ .Values.Cluster.imageHub.namespace | quote }} 
{{- end }}
{{- if .Values.Cluster.regionDatabase.enable }}
    regionDatabase:
      host: {{  required ".Values.Cluster.regionDatabase.host cannot be empty!" .Values.Cluster.regionDatabase.host }}
      name: {{ .Values.Cluster.regionDatabase.name | quote }}
      password: {{ .Values.Cluster.regionDatabase.password | quote }}
      port: {{ .Values.Cluster.regionDatabase.port }}
      username: {{ .Values.Cluster.regionDatabase.username | quote }}
{{- end }}
{{- if .Values.Cluster.uiDatabase.enable }}
    uiDatabase:
      host: {{ required ".Values.Cluster.uiDatabase.host cannot be empty!" .Values.Cluster.uiDatabase.host }}
      name: {{ .Values.Cluster.uiDatabase.name | quote }}
      password: {{ .Values.Cluster.uiDatabase.password | quote }}
      port: {{ .Values.Cluster.uiDatabase.port }}
      username: {{ .Values.Cluster.uiDatabase.username | quote }}
{{- end }}
    nodesForChaos:
{{ toYaml .Values.Cluster.nodesForChaos | indent 4 }}
    nodesForGateway:
{{ toYaml .Values.Cluster.nodesForGateway | indent 4 }}
    rainbondImageRepository: {{ .Values.Cluster.rainbondImageRepository }}
    installVersion: {{ .Values.Cluster.installVersion }}
    suffixHTTPHost: ""

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
