#############################################
# 
# Copyright 2023 Goodrain Co., Ltd.
# 
# This version of the GNU Lesser General Public License incorporates
# the terms and conditions of version 3 of the GNU General Public License.
# 
#############################################


apiVersion: v1
items:
- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: local-path-provisioner
    name: local-path-provisioner
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/local-path-provisioner:v0.0.29
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: 1
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: minio
    name: minio
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/minio:RELEASE.2024-09-22T00-33-43Z
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: 1
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-hub      
    name: rbd-hub
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/registry:2.6.2
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: {{ .Values.Cluster.replicas }}
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-mq
    name: rbd-mq
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-mq:{{ .Values.Cluster.installVersion }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: {{ .Values.Cluster.replicas }}
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-monitor
    name: rbd-monitor
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-monitor:v2.20.0
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: 1
    priorityComponent: true

{{- if not (or .Values.Cluster.uiDatabase.enable .Values.Cluster.regionDatabase.enable) }}
- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-db
    name: rbd-db
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-db:8.0.19
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: 1
    priorityComponent: true
{{- end }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-chaos      
    name: rbd-chaos
    namespace: {{ .Release.Namespace }}
  spec:
    {{- if .Values.useK3sContainerd }}
    volumeMounts:
    - name: containerdsock
      mountPath: /run/containerd
    volumes:
    - name: containerdsock
      hostPath:
        path: /var/run/k3s/containerd
        type: Directory
    {{- end }}
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-chaos:{{ .Values.Cluster.installVersion }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: {{ .Values.Cluster.replicas }}
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-worker      
    name: rbd-worker
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-worker:{{ .Values.Cluster.installVersion }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: {{ .Values.Cluster.replicas }}
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-eventlog      
    name: rbd-eventlog
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-eventlog:{{ .Values.Cluster.installVersion }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: 1
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-api
    name: rbd-api
    namespace: {{ .Release.Namespace }}
  spec:  
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-api:{{ .Values.Cluster.installVersion }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: {{ .Values.Cluster.replicas }}
    priorityComponent: true

{{- if .Values.Component.rbd_app_ui.enable }}
- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-app-ui
    name: rbd-app-ui
    namespace: {{ .Release.Namespace }}
  spec:
    env:
    - name: DB_TYPE
      value: mysql
    image: {{ .Values.Cluster.rainbondImageRepository }}/rainbond:{{ .Values.Cluster.installVersion }}-allinone
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: 1
    priorityComponent: false
{{- end }}

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

