#############################################
# 
# Copyright 2023 Goodrain Co., Ltd.
# 
# This version of the GNU Lesser General Public License incorporates
# the terms and conditions of version 3 of the GNU General Public License.
# 
#############################################


apiVersion: v1
items:
- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: local-path-provisioner
    name: local-path-provisioner
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/local-path-provisioner:v0.0.30
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: 1
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: minio
    name: minio
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/minio:RELEASE.2023-10-24T04-42-36Z
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: 1
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-gateway
    name: rbd-gateway
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/apisix-ingress-controller:v1.8.3@{{ .Values.Cluster.rainbondImageRepository }}/apisix:3.9.1-debian-fix
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    priorityComponent: true
    replicas: {{ .Values.Cluster.replicas }}

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-hub      
    name: rbd-hub
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/registry:2.6.2
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: {{ .Values.Cluster.replicas }}
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-mq
    name: rbd-mq
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-mq:{{ .Values.Cluster.installVersion }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: {{ .Values.Cluster.replicas }}
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-monitor
    name: rbd-monitor
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-monitor:v2.20.0
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: 1
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-chaos      
    name: rbd-chaos
    namespace: {{ .Release.Namespace }}
  spec:
    args:
    - --db-type=sqlite
    volumeMounts:
    - mountPath: /db
      name: sqlite    
    - name: containerdsock
      mountPath: /run/containerd
    volumes:
    - name: containerdsock
      hostPath:
        path: /var/run/k3s/containerd
        type: Directory
    - hostPath:
        path: /opt/rainbond/region
        type: DirectoryOrCreate
      name: sqlite
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-chaos:{{ .Values.Cluster.installVersion }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: {{ .Values.Cluster.replicas }}
    priorityComponent: true

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-worker      
    name: rbd-worker
    namespace: {{ .Release.Namespace }}
  spec:
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-worker:{{ .Values.Cluster.installVersion }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: {{ .Values.Cluster.replicas }}
    priorityComponent: true
    args:
    - --db-type=sqlite
    volumeMounts:
    - mountPath: /db
      name: sqlite
    volumes:
    - hostPath:
        path: /opt/rainbond/region
        type: DirectoryOrCreate
      name: sqlite

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-api
    name: rbd-api
    namespace: {{ .Release.Namespace }}
  spec:  
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-api:{{ .Values.Cluster.installVersion }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: {{ .Values.Cluster.replicas }}
    priorityComponent: true
    args:
    - --db-type=sqlite
    volumeMounts:
    - mountPath: /db
      name: sqlite
    volumes:
    - hostPath:
        path: /opt/rainbond/region
        type: DirectoryOrCreate
      name: sqlite

{{- if .Values.Component.rbd_app_ui.enable }}
- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-app-ui
    name: rbd-app-ui
    namespace: {{ .Release.Namespace }}
  spec:
    volumes:
    - name: app
      hostPath:
        path: /opt/rainbond/rainbonddata
        type: DirectoryOrCreate
    image: {{ .Values.Cluster.rainbondImageRepository }}/rainbond:{{ .Values.Cluster.installVersion }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    replicas: 1
    priorityComponent: false
{{- end }}

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

