#############################################
# 
# Copyright 2023 Goodrain Co., Ltd.
# 
# This version of the GNU Lesser General Public License incorporates
# the terms and conditions of version 3 of the GNU General Public License.
# 
#############################################
{{- if .Values.Component.region_all.enable }}
apiVersion: v1
items:
- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-gateway
      priorityComponent: "true"
    name: rbd-gateway
    namespace: {{ .Release.Namespace }}
  spec:
    {{- if .Values.Component.rbd_gateway.args }}
    args:
    {{- range .Values.Component.rbd_gateway.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_gateway.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_gateway.env }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_gateway.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_gateway.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_gateway.volumes }}
    volumes:
    {{- range $key,$value := .Values.Component.rbd_gateway.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rbd_gateway.apisix_ingress_image }}@{{ .Values.Component.rbd_gateway.apisix_image }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    priorityComponent: true
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-hub      
      priorityComponent: "true"
    name: rbd-hub
    namespace: {{ .Release.Namespace }}
  spec:
    {{- if .Values.Component.rbd_hub.args }}
    args:
    {{- range .Values.Component.rbd_hub.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_hub.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_hub.env }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_hub.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_hub.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_hub.volumes }}
    volumes:
    {{- range $key,$value := .Values.Component.rbd_hub.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_hub.image }}
    image: {{ .Values.Component.rbd_hub.image }}
    {{- else }}
    image: {{ .Values.Cluster.rainbondImageRepository }}/registry:2.6.2
    {{- end }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    priorityComponent: true
    replicas: {{ .Values.Cluster.replicas }}

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-mq
    name: rbd-mq
    namespace: {{ .Release.Namespace }}
  spec:
    {{- if .Values.Component.rbd_mq.args }}
    args:
    {{- range .Values.Component.rbd_mq.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_mq.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_mq.env }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_mq.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_mq.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_mq.volumes }}
    volumes:
    {{- range $key,$value := .Values.Component.rbd_mq.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_mq.image }}
    image: {{ .Values.Component.rbd_mq.image }}
    {{- else }}
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-mq:{{ .Values.Cluster.installVersion }}
    {{- end }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    priorityComponent: false
    replicas: {{ .Values.Cluster.replicas }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-resource-proxy
    name: rbd-resource-proxy
    namespace: {{ .Release.Namespace }}
  spec:
    {{- if .Values.Component.rbd_resource_proxy.args }}
    args:
    {{- range .Values.Component.rbd_resource_proxy.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_resource_proxy.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_resource_proxy.env }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_resource_proxy.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_resource_proxy.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_resource_proxy.volumes }}
    volumes:
    {{- range $key,$value := .Values.Component.rbd_resource_proxy.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_resource_proxy.image }}
    image: {{ .Values.Component.rbd_resource_proxy.image }}
    {{- else }}
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-resource-proxy:{{ .Values.Cluster.installVersion }}
    {{- end }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    priorityComponent: false
    replicas: 1 
      
- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-webcli
    name: rbd-webcli
    namespace: {{ .Release.Namespace }}
  spec:
    {{- if .Values.Component.rbd_webcli.args }}
    args:
    {{- range .Values.Component.rbd_webcli.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_webcli.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_webcli.env }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_webcli.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_webcli.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_webcli.volumes }}
    volumes:
    {{- range $key,$value := .Values.Component.rbd_webcli.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_webcli.image }}
    image: {{ .Values.Component.rbd_webcli.image }}
    {{- else }}
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-webcli:{{ .Values.Cluster.installVersion }}
    {{- end }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    priorityComponent: false
    replicas: {{ .Values.Cluster.replicas }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-monitor
    name: rbd-monitor
    namespace: {{ .Release.Namespace }}
  spec:
    {{- if .Values.Component.rbd_monitor.args }}
    args:
    {{- range .Values.Component.rbd_monitor.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_monitor.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_monitor.env }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_monitor.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_monitor.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_monitor.volumes }}
    volumes:
    {{- range $key,$value := .Values.Component.rbd_monitor.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-monitor:v2.20.0
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    priorityComponent: false
    replicas: 1


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-chaos      
    name: rbd-chaos
    namespace: {{ .Release.Namespace }}
  spec:
    args:
    - --es-url={{ .Values.Cluster.elasticsearch.region.host }}
    - --es-username={{ .Values.Cluster.elasticsearch.region.username }}
    - --es-password={{ .Values.Cluster.elasticsearch.region.password }}
    {{- range .Values.Component.rbd_chaos.args }}
    - {{ . | toString  }}
    {{- end }}
    {{- if .Values.Component.rbd_chaos.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_chaos.env }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    {{- if .Values.useK3sContainerd }}
    volumeMounts:
    - name: containerdsock
      mountPath: /run/containerd
    volumes:
    - name: containerdsock
      hostPath:
        path: /var/run/k3s/containerd
        type: Directory
    {{- end }}
    {{- if .Values.Component.rbd_chaos.image }}
    image: {{ .Values.Component.rbd_chaos.image }}
    {{- else }}
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-chaos:{{ .Values.Cluster.installVersion }}
    {{- end }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    priorityComponent: false
    replicas: {{ .Values.Cluster.replicas }}

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-worker      
    name: rbd-worker
    namespace: {{ .Release.Namespace }}
  spec:
    {{- if .Values.Component.rbd_worker.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_worker.env }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    args:
    - --es-url={{ .Values.Cluster.elasticsearch.region.host }}
    - --es-username={{ .Values.Cluster.elasticsearch.region.username }}
    - --es-password={{ .Values.Cluster.elasticsearch.region.password }}
    {{- range .Values.Component.rbd_worker.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- if .Values.Component.rbd_worker.env }}
    env:
    - key: CLUSTER_STATUS
      value: {{ .Values.Cluster.role }}
    {{- range $key,$value := .Values.Component.rbd_worker.env }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_worker.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_worker.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_worker.volumes }}
    volumes:
    {{- range $key,$value := .Values.Component.rbd_worker.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_worker.image }}
    image: {{ .Values.Component.rbd_worker.image }}
    {{- else }}
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-worker:{{ .Values.Cluster.installVersion }}
    {{- end}}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    priorityComponent: false
    replicas: {{ .Values.Cluster.replicas }}

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-eventlog      
    name: rbd-eventlog
    namespace: {{ .Release.Namespace }}
  spec:
    args:
    - --es-url={{ .Values.Cluster.elasticsearch.region.host }}
    - --es-username={{ .Values.Cluster.elasticsearch.region.username }}
    - --es-password={{ .Values.Cluster.elasticsearch.region.password }}
    {{- range .Values.Component.rbd_eventlog.args }}
    - {{ . | toString  }}
    {{- end }}
    {{- if .Values.Component.rbd_eventlog.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_eventlog.env }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_eventlog.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_eventlog.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_eventlog.volumes }}
    volumes:
    {{- range $key,$value := .Values.Component.rbd_eventlog.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_eventlog.image }}
    image: {{ .Values.Component.rbd_eventlog.image }}
    {{- else }}
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-eventlog:{{ .Values.Cluster.installVersion }}
    {{- end }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    priorityComponent: false
    replicas: {{ .Values.Cluster.replicas }}

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-api
    name: rbd-api
    namespace: {{ .Release.Namespace }}
  spec:  
    args:
    - --es-url={{ .Values.Cluster.elasticsearch.region.host }}
    - --es-username={{ .Values.Cluster.elasticsearch.region.username }}
    - --es-password={{ .Values.Cluster.elasticsearch.region.password }}
    {{- range .Values.Component.rbd_api.args }}
    - {{ . | toString  }}
    {{- end }}
    {{- if .Values.Component.rbd_api.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_api.env }}
    - name: {{ $key }}
      value: "{{ $value }}"
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_api.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_api.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_api.volumes }}
    volumes:
    {{- range $key,$value := .Values.Component.rbd_api.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_api.image }}
    image: {{ .Values.Component.rbd_api.image }}
    {{- else }}
    image: {{ .Values.Cluster.rainbondImageRepository }}/rbd-api:{{ .Values.Cluster.installVersion }}
    {{- end }}
    imagePullPolicy: {{ .Values.Cluster.imagePullPolicy }}
    priorityComponent: false
    replicas: {{ .Values.Cluster.replicas }}

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
{{- end }}